name: 'Status Checks'
description: 'Verify GitHub status checks for builds, tests, and changesets (does not create statuses)'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  sha:
    description: 'Commit SHA to verify status checks against'
    required: false
    default: ''
  pr-number:
    description: 'PR number to verify status checks against (alternative to SHA)'
    required: false
    default: ''
  wait-for-checks:
    description: 'Whether to wait for checks to complete'
    required: false
    default: 'true'
  timeout:
    description: 'Timeout in seconds when waiting for checks'
    required: false
    default: '300'
  workflow-name:
    description: 'Current workflow name for filtering when waiting for checks'
    required: false
    default: ''
  min-checks:
    description: 'Minimum number of non-workflow checks required'
    required: false
    default: '3'

outputs:
  pr-sha:
    description: 'The SHA of the PR head'
    value: ${{ steps.get-sha.outputs.sha }}

runs:
  using: "composite"
  steps:
    # Get SHA from PR if needed
    - name: Get PR SHA if PR number provided
      id: get-sha
      shell: bash
      run: |
        if [ -n "${{ inputs.sha }}" ]; then
          echo "Using provided SHA: ${{ inputs.sha }}"
          echo "sha=${{ inputs.sha }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ inputs.pr-number }}" ]; then
          echo "Getting SHA from PR #${{ inputs.pr-number }}"
          PR_SHA=$(gh pr view ${{ inputs.pr-number }} --json headRefOid --jq .headRefOid)
          echo "Got SHA: $PR_SHA"
          echo "sha=$PR_SHA" >> $GITHUB_OUTPUT
        else
          echo "Error: Either 'sha' or 'pr-number' must be provided"
          exit 1
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    # Wait for checks to complete
    - name: Wait for checks to complete
      if: inputs.wait-for-checks == 'true'
      shell: bash
      run: |
        if [ -z "${{ inputs.workflow-name }}" ]; then
          # Extract workflow name from GITHUB_WORKFLOW
          WORKFLOW_NAME="${{ github.workflow }}"
        else
          WORKFLOW_NAME="${{ inputs.workflow-name }}"
        fi
        
        echo "Waiting for checks to complete with workflow name: $WORKFLOW_NAME"
        
        # Use the workflow-aware check handling script
        bash .github/scripts/branch/wait-checks.sh \
          --repo "${{ inputs.repository }}" \
          --sha "${{ steps.get-sha.outputs.sha }}" \
          --workflow "$WORKFLOW_NAME" \
          --timeout "${{ inputs.timeout }}" \
          --min-checks "${{ inputs.min-checks }}"
      env:
        GH_TOKEN: ${{ inputs.github-token }} 