[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 