name: 'Changeset Management'
description: 'Manages changesets for versioning and publishing'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  base-branch:
    description: 'Base branch to compare against'
    required: false
    default: 'main'
  since-commit:
    description: 'Generate changesets since this commit'
    required: false
    default: ''
  create-release:
    description: 'Whether to create a release'
    required: false
    default: 'false'
  package-name:
    description: 'Package to create changeset for (all, or specific package)'
    required: false
    default: 'all'
  version-type:
    description: 'Version type for the changeset (major, minor, patch)'
    required: false
    default: 'patch'
  publish:
    description: 'Whether to publish the package'
    required: false
    default: 'false'
  auto-changeset-prefix:
    description: 'Prefix for auto-generated changeset files'
    required: false
    default: 'auto-'

outputs:
  has-changesets:
    description: 'Whether any changesets were found'
    value: ${{ steps.check-changesets.outputs.has_changesets }}
  has-auto-changesets:
    description: 'Whether any auto-generated changesets were found'
    value: ${{ steps.check-changesets.outputs.has_auto_changesets }}
  published:
    description: 'Whether any packages were published'
    value: ${{ steps.changesets.outputs.published }}
  pr-number:
    description: 'PR number if one was created'
    value: ${{ steps.find-pr.outputs.pr_number }}
  branch-name:
    description: 'Branch name used for the changeset'
    value: ${{ steps.generate-changeset.outputs.branch_name }}

runs:
  using: "composite"
  steps:
    # Check for existing changesets using our script
    - name: Check for changesets
      id: check-changesets
      shell: bash
      run: |
        OUTPUT=$(bash .github/scripts/version/check-changesets.sh \
          --auto-changeset-prefix "${{ inputs.auto-changeset-prefix }}")
        
        # Parse the output and set it to GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT

    # Generate changeset using our script (if requested)
    - name: Generate changeset
      id: generate-changeset
      if: inputs.since-commit != ''
      shell: bash
      run: |
        OUTPUT=$(bash .github/scripts/version/generate-changeset.sh \
          --since-commit "${{ inputs.since-commit }}" \
          --package-name "${{ inputs.package-name }}" \
          --version-type "${{ inputs.version-type }}" \
          --auto-changeset-prefix "${{ inputs.auto-changeset-prefix }}")
        
        # Parse the output and set it to GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT

    # Validate changesets using our script
    - name: Validate changesets
      id: validate-changesets
      if: steps.check-changesets.outputs.has_changesets == 'true' || steps.generate-changeset.outputs.changeset_created == 'true'
      shell: bash
      run: |
        bash .github/scripts/version/validate-changesets.sh

    # Run version/release if needed using our script
    - name: Create Release or Version PR
      id: changesets
      if: (steps.check-changesets.outputs.has_changesets == 'true' || steps.generate-changeset.outputs.changeset_created == 'true') && inputs.create-release == 'true'
      shell: bash
      run: |
        if [ "${{ inputs.publish }}" == "true" ]; then
          echo "Versioning and publishing packages..."
          # Use update-packages.sh for versioning
          bash .github/scripts/version/update-packages.sh
          
          # Use publish-packages.sh for publishing
          RESULT=$(bash .github/scripts/version/publish-packages.sh \
            --package-path "${{ inputs.package-name }}")
          
          echo "published=true" >> $GITHUB_OUTPUT
        else
          echo "Versioning packages only..."
          bash .github/scripts/version/update-packages.sh
          echo "published=false" >> $GITHUB_OUTPUT
        fi
        
        # Check if changeset-release/main branch exists and push it
        if git show-ref --verify --quiet refs/heads/changeset-release/main; then
          echo "Pushing changeset-release/main branch..."
          git push origin changeset-release/main
        fi

    # Find any version PRs using our script
    - name: Find open version PRs
      id: find-pr
      shell: bash
      run: |
        OUTPUT=$(bash .github/scripts/pr/find-pr.sh \
          --token "${{ inputs.github-token }}" \
          --repo "${{ inputs.repository }}" \
          --title "chore: version packages")
        
        # Parse the output and set it to GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT

    # Create status checks for PR if found using our script
    - name: Create Changesets Status Check
      if: steps.find-pr.outputs.has_pr == 'true'
      shell: bash
      run: |
        # First get the PR SHA using our script
        PR_SHA=$(bash .github/scripts/branch/get-sha.sh \
          --token "${{ inputs.github-token }}" \
          --repo "${{ inputs.repository }}" \
          --pr-number "${{ steps.find-pr.outputs.pr_number }}")
        
        # Then create the status check using our script
        bash .github/scripts/branch/force-status.sh \
          --token "${{ inputs.github-token }}" \
          --repo "${{ inputs.repository }}" \
          --sha "$PR_SHA" \
          --context "Test Changesets" \
          --description "Changesets validated successfully" \
          --state "success" \
          --target-url "${{ github.server_url }}/${{ inputs.repository }}/actions/runs/${{ github.run_id }}" 