name: "Process Version Changes"
description: "Process version changes, create tags, and publish packages"

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  publish-packages:
    description: "Whether to publish packages"
    required: false
    default: "true"
  create-releases:
    description: "Whether to create GitHub releases"
    required: false
    default: "true"

outputs:
  packages-tagged:
    description: "Number of packages tagged"
    value: ${{ steps.process-versions.outputs.packages_tagged }}
  tags-created:
    description: "Comma-separated list of created tags"
    value: ${{ steps.process-versions.outputs.tags_created }}
  releases-created:
    description: "Number of releases created"
    value: ${{ steps.process-versions.outputs.releases_created }}
  error-message:
    description: "Error message, if any"
    value: ${{ steps.process-versions.outputs.error-message }}

runs:
  using: "composite"
  steps:
    - name: "Make version script executable"
      shell: bash
      run: chmod +x .github/scripts/version/process-version-changes.sh
    
    - name: "Process version changes"
      id: process-versions
      shell: bash
      run: |
        .github/scripts/version/process-version-changes.sh \
          --token "${{ inputs.github-token }}" \
          ${{ inputs.publish-packages == 'false' && '--no-publish' || '' }} \
          ${{ inputs.create-releases == 'false' && '--no-releases' || '' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }} 