name: 'Status Checks'
description: 'Manages GitHub status checks for builds, tests, and changesets'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  repository:
    description: 'Repository name (owner/repo)'
    required: true
  sha:
    description: 'Commit SHA to add status checks to'
    required: false
    default: ''
  pr-number:
    description: 'PR number to add status checks to (alternative to SHA)'
    required: false
    default: ''
  contexts:
    description: 'JSON array of context names to create'
    required: false
    default: '["Build Packages", "Test / Run Tests", "Test Changesets"]'
  descriptions:
    description: 'JSON array of descriptions for each context'
    required: false
    default: '["Build completed successfully", "Tests passed successfully", "Changesets validated successfully"]'
  context-prefix:
    description: 'Prefix to add to all context names'
    required: false
    default: ''
  wait-for-checks:
    description: 'Whether to wait for checks to complete'
    required: false
    default: 'false'
  timeout:
    description: 'Timeout in seconds when waiting for checks'
    required: false
    default: '300'
  workflow-name:
    description: 'Current workflow name for filtering when waiting for checks'
    required: false
    default: ''
  min-checks:
    description: 'Minimum number of non-workflow checks required'
    required: false
    default: '3'

outputs:
  pr-sha:
    description: 'The SHA of the PR head'
    value: ${{ steps.get-sha.outputs.sha }}

runs:
  using: "composite"
  steps:
    # Get SHA from PR if needed
    - name: Get PR SHA if PR number provided
      id: get-sha
      shell: bash
      run: |
        if [ -n "${{ inputs.sha }}" ]; then
          echo "Using provided SHA: ${{ inputs.sha }}"
          echo "sha=${{ inputs.sha }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ inputs.pr-number }}" ]; then
          echo "Getting SHA from PR #${{ inputs.pr-number }}"
          PR_SHA=$(gh pr view ${{ inputs.pr-number }} --json headRefOid --jq .headRefOid)
          echo "Got SHA: $PR_SHA"
          echo "sha=$PR_SHA" >> $GITHUB_OUTPUT
        else
          echo "Error: Either 'sha' or 'pr-number' must be provided"
          exit 1
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    # Create status checks
    - name: Create status checks
      shell: bash
      run: |
        CONTEXTS=$(echo '${{ inputs.contexts }}' | jq -c '.')
        DESCRIPTIONS=$(echo '${{ inputs.descriptions }}' | jq -c '.')
        
        CONTEXTS_LENGTH=$(echo $CONTEXTS | jq 'length')
        DESCRIPTIONS_LENGTH=$(echo $DESCRIPTIONS | jq 'length')
        
        # Parse contexts
        for (( i=0; i<$CONTEXTS_LENGTH; i++ )); do
          CONTEXT=$(echo $CONTEXTS | jq -r ".[$i]")
          
          # Get description (if available)
          DESCRIPTION=""
          if [ $i -lt $DESCRIPTIONS_LENGTH ]; then
            DESCRIPTION=$(echo $DESCRIPTIONS | jq -r ".[$i]")
          else
            DESCRIPTION="Status check passed"
          fi
          
          # Add prefix if provided
          if [ -n "${{ inputs.context-prefix }}" ]; then
            CONTEXT="${{ inputs.context-prefix }}$CONTEXT"
          fi
          
          echo "Creating status check: $CONTEXT"
          gh api \
            --method POST \
            /repos/${{ inputs.repository }}/statuses/${{ steps.get-sha.outputs.sha }} \
            -f state=success \
            -f context="$CONTEXT" \
            -f description="$DESCRIPTION" \
            -f target_url="${{ github.server_url }}/${{ inputs.repository }}/actions/runs/${{ github.run_id }}"
        done
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    # Wait for checks if requested
    - name: Wait for checks to complete
      if: inputs.wait-for-checks == 'true'
      shell: bash
      run: |
        if [ -z "${{ inputs.workflow-name }}" ]; then
          # Extract workflow name from GITHUB_WORKFLOW
          WORKFLOW_NAME="${{ github.workflow }}"
        else
          WORKFLOW_NAME="${{ inputs.workflow-name }}"
        fi
        
        echo "Waiting for checks to complete with workflow name: $WORKFLOW_NAME"
        
        # Use the workflow-aware check handling script
        bash .github/scripts/branch/wait-checks.sh \
          --repo "${{ inputs.repository }}" \
          --sha "${{ steps.get-sha.outputs.sha }}" \
          --workflow "$WORKFLOW_NAME" \
          --timeout "${{ inputs.timeout }}" \
          --min-checks "${{ inputs.min-checks }}"
      env:
        GH_TOKEN: ${{ inputs.github-token }} 