name: 'Preserve Changeset Config'
description: 'Ensures the changeset config stays with independent versioning'

runs:
  using: "composite"
  steps:
    - name: Preserve changeset configuration
      shell: bash
      run: |
        echo "Ensuring changeset config uses independent versioning..."
        # Create a backup of our config
        cp .changeset/config.json .changeset/config.json.bak
        # Update the config to use independent versioning
        cat > .changeset/config.json << EOF
        {
          "$schema": "https://unpkg.com/@changesets/config@3.1.1/schema.json",
          "changelog": "@changesets/cli/changelog",
          "commit": true,
          "fixed": [],
          "linked": [],
          "access": "restricted",
          "baseBranch": "main",
          "updateInternalDependencies": "patch",
          "ignore": []
        }
        EOF
        # Check if the config was changed
        if ! cmp -s .changeset/config.json .changeset/config.json.bak; then
          echo "Config was restored to independent versioning"
          git add .changeset/config.json
          git commit -m "chore: restore independent versioning in changeset config"
          git push
        else
          echo "Config already has independent versioning"
        fi
        rm .changeset/config.json.bak 