name: 'Build and Test'
description: 'Handles build and test operations for packages'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: 'lts/*'
  pnpm-version:
    description: 'PNPM version to use'
    required: false
    default: '8.15.4'
  build-command:
    description: 'Command to run for building packages'
    required: false
    default: 'pnpm run build'
  test-command:
    description: 'Command to run for testing packages'
    required: false
    default: 'pnpm test'
  artifact-name:
    description: 'Name of the artifact to store build outputs'
    required: false
    default: 'package-builds'
  artifact-path:
    description: 'Path pattern for artifacts to upload'
    required: false
    default: 'packages/*/dist'

outputs:
  build-result:
    description: 'Result of the build operation (success/failure)'
    value: ${{ steps.build.outputs.result }}
  test-result:
    description: 'Result of the test operation (success/failure)'
    value: ${{ steps.test.outputs.result }}

runs:
  using: "composite"
  steps:
    # Setup environment using our script
    - name: Setup environment
      id: setup
      shell: bash
      run: |
        # Run the setup script and capture only its actual output variables
        # All logs and progress messages are directed to stderr
        TOKEN="${{ inputs.github-token }}"
        NODE_VERSION="${{ inputs.node-version }}"
        PNPM_VERSION="${{ inputs.pnpm-version }}"
        
        # Run script and filter only properly formatted output lines for GITHUB_OUTPUT
        bash .github/scripts/maintenance/setup-environment.sh \
          --github-token "$TOKEN" \
          --node-version "$NODE_VERSION" \
          --pnpm-version "$PNPM_VERSION" 2>&1 | grep -E "^[a-zA-Z0-9_-]+=.+" >> $GITHUB_OUTPUT || true

    # Build step using our script
    - name: Build packages
      id: build
      shell: bash
      run: |
        # Debug what command is being used
        echo "Using build command: ${{ inputs.build-command }}" >&2
        
        # Create a file to properly handle command with spaces
        BUILD_COMMAND_FILE=$(mktemp)
        echo '${{ inputs.build-command }}' > "$BUILD_COMMAND_FILE"
        BUILD_COMMAND=$(cat "$BUILD_COMMAND_FILE")
        rm "$BUILD_COMMAND_FILE"
        
        # Run the build script with proper quoting for the command
        bash .github/scripts/maintenance/build-packages.sh --build-command "$BUILD_COMMAND" >> $GITHUB_OUTPUT
        
        # Check the build result output for failure and fail explicitly
        if grep -q "result=failure" $GITHUB_OUTPUT; then
          echo "Build failed! Failing the workflow."
          exit 1
        fi

    # Upload artifacts using GitHub's native action
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # Test step using our script
    - name: Run tests
      id: test
      shell: bash
      run: |
        # Debug what command is being used
        echo "Using test command: ${{ inputs.test-command }}" >&2
        
        # Create a file to properly handle command with spaces
        TEST_COMMAND_FILE=$(mktemp)
        echo '${{ inputs.test-command }}' > "$TEST_COMMAND_FILE"
        TEST_COMMAND=$(cat "$TEST_COMMAND_FILE")
        rm "$TEST_COMMAND_FILE"
        
        # Run the test script with proper quoting for the command
        bash .github/scripts/maintenance/run-tests.sh --test-command "$TEST_COMMAND" >> $GITHUB_OUTPUT
        
        # Check the test result output for failure and fail explicitly
        if grep -q "result=failure" $GITHUB_OUTPUT; then
          echo "Tests failed! Failing the workflow."
          exit 1
        fi

    # Create build status check if PR_SHA is available
    - name: Create Build Status Check
      if: ${{ env.PR_SHA != '' }}
      shell: bash
      run: |
        if [ -n "$PR_SHA" ]; then
          bash .github/scripts/branch/force-status.sh \
            --token "${{ inputs.github-token }}" \
            --repo "${{ github.repository }}" \
            --sha "$PR_SHA" \
            --context "Build Packages" \
            --description "Build completed successfully" \
            --state "success" \
            --target-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi
      env:
        PR_SHA: ${{ env.PR_SHA }}

    # Create test status check if PR_SHA is available
    - name: Create Test Status Check
      if: ${{ env.PR_SHA != '' }}
      shell: bash
      run: |
        if [ -n "$PR_SHA" ]; then
          bash .github/scripts/branch/force-status.sh \
            --token "${{ inputs.github-token }}" \
            --repo "${{ github.repository }}" \
            --sha "$PR_SHA" \
            --context "Test / Run Tests" \
            --description "Tests passed successfully" \
            --state "success" \
            --target-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi
      env:
        PR_SHA: ${{ env.PR_SHA }}