name: 'Create Releases and Publish'
description: 'Create GitHub releases for existing tags and publish packages to GitHub npm'

inputs:
  github-token:
    description: 'GitHub token for creating releases and commits'
    required: true
  npm-token:
    description: 'NPM token for publishing packages'
    required: true
  release-type:
    description: 'Type of release to create (auto, patch, minor, major, etc.)'
    required: false
    default: 'auto'

outputs:
  has-releases:
    description: 'Whether any releases were created'
    value: ${{ steps.create-releases.outputs.has_new_releases }}
  releases-count:
    description: 'Number of releases created'
    value: ${{ steps.create-releases.outputs.releases_count }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://npm.pkg.github.com'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: '8.15.4'
        
    - name: Install dependencies
      shell: bash
      run: pnpm install
    
    - name: Verify Lerna installation
      shell: bash
      run: |
        echo "Checking Lerna installation..."
        pnpm lerna --version || echo "Lerna not installed via pnpm, trying npx"
        npx lerna --version || echo "Lerna not available via npx either, proceeding anyway"
        
        echo "Listing available packages..."
        pnpm lerna list --json --loglevel=info || echo "Unable to list packages with lerna, will use git tags instead"
        
        echo "Checking pnpm version..."
        pnpm --version
        echo "Checking Node.js version..."
        node --version
    
    - name: Test Lerna commands
      shell: bash
      run: |
        if [ -f "tests/pipeline-tests/test-lerna-commands.sh" ]; then
          chmod +x tests/pipeline-tests/test-lerna-commands.sh
          ./tests/pipeline-tests/test-lerna-commands.sh || echo "Lerna command test failed but continuing"
        else
          echo "Lerna test script not found, skipping tests"
        fi
    
    # Fetch all tags to ensure we have the complete history
    - name: Fetch all tags
      shell: bash
      run: |
        echo "Fetching all tags from remote..."
        git fetch --tags --force
        
        # List tags for debugging
        echo "All package tags in repository:"
        git tag | grep -E "^@" || echo "No package tags found"
        
        # Count tags to verify
        PACKAGE_TAG_COUNT=$(git tag | grep -E "^@" | wc -l | tr -d '[:space:]')
        echo "Total package tags in repository: $PACKAGE_TAG_COUNT"
    
    # Create GitHub releases for existing tags
    - name: Create GitHub releases
      id: create-releases
      shell: bash
      run: |
        chmod +x .github/scripts/ci/manage-github-releases.sh
        .github/scripts/ci/manage-github-releases.sh --verbose || {
          echo "Release script failed but we're continuing the workflow"
          # Create default outputs if the script failed
          if [ -n "$GITHUB_OUTPUT" ]; then
            echo "releases_count=0" >> $GITHUB_OUTPUT
            echo "has_new_releases=false" >> $GITHUB_OUTPUT
          fi
        }
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    
    # Publish to GitHub npm packages
    - name: Publish to GitHub npm packages
      id: publish-npm
      shell: bash
      run: |
        # Only publish if releases were created
        if [ "${{ steps.create-releases.outputs.has_new_releases }}" == "true" ]; then
          # Build packages before publishing
          echo "🏗️ Building packages..."
          pnpm build || echo "Build failed but continuing with publish attempt"
          
          # Publish to GitHub npm registry with error handling
          echo "📦 Publishing packages from tags to GitHub npm registry..."
          pnpm lerna publish from-package --yes --loglevel=info --ignore-scripts --registry=https://npm.pkg.github.com || echo "Some packages may already be published, continuing"
        else
          echo "No new releases created, skipping npm publish step"
        fi
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        GH_TOKEN: ${{ inputs.github-token }} 