name: 'Create Releases and Publish'
description: 'Create GitHub releases for existing tags and publish packages to GitHub npm'

inputs:
  github-token:
    description: 'GitHub token for creating releases and commits'
    required: true
  npm-token:
    description: 'NPM token for publishing packages'
    required: true
  release-type:
    description: 'Type of release to create (auto, patch, minor, major, etc.)'
    required: false
    default: 'auto'

outputs:
  has-releases:
    description: 'Whether any releases were created'
    value: ${{ steps.create-releases.outputs.has_new_releases }}
  releases-count:
    description: 'Number of releases created'
    value: ${{ steps.create-releases.outputs.releases_count }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        registry-url: 'https://npm.pkg.github.com'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: '8.15.4'
        
    - name: Install dependencies
      shell: bash
      run: pnpm install
    
    - name: Verify Lerna installation
      shell: bash
      run: |
        echo "Checking Lerna installation..."
        pnpm lerna --version
        echo "Listing available packages..."
        pnpm lerna list --json --loglevel=info
        echo "Checking pnpm version..."
        pnpm --version
        echo "Checking Node.js version..."
        node --version
    
    - name: Test Lerna commands 
      shell: bash
      run: |
        chmod +x tests/pipeline-tests/test-lerna-commands.sh
        ./tests/pipeline-tests/test-lerna-commands.sh
    
    # Create GitHub releases for existing tags
    - name: Create GitHub releases
      id: create-releases
      shell: bash
      run: |
        chmod +x .github/scripts/ci/manage-github-releases.sh
        .github/scripts/ci/manage-github-releases.sh --verbose
      env:
        GH_TOKEN: ${{ inputs.github-token }}
    
    # Publish to GitHub npm packages
    - name: Publish to GitHub npm packages
      if: steps.create-releases.outputs.has_new_releases == 'true'
      id: publish-npm
      shell: bash
      run: |
        # Build packages before publishing
        echo "🏗️ Building packages..."
        pnpm build
        
        # Publish to GitHub npm registry
        echo "📦 Publishing packages from tags to GitHub npm registry..."
        pnpm lerna publish from-package --yes --loglevel=info --ignore-scripts --registry=https://npm.pkg.github.com || echo "Some packages may already be published, continuing"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        GH_TOKEN: ${{ inputs.github-token }} 