#!/bin/sh

# Run commitlint validation
npx --no -- commitlint --edit $1

echo "🔍 Validating commit message format..."

# Exit if commitlint failed
if [ $? -ne 0 ]; then
  echo "❌ Commit message validation failed."
  exit 1
fi

echo "✅ Commit message validation passed."
exit 0
