name: Auto PR Creation and Merge

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    name: Create and Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PR_CREATION_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
      
      - name: Extract commit details
        id: commit_details
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE<<EOF" >> "$GITHUB_ENV"
          echo "$COMMIT_MSG" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
          
          # Extract PR title from commit message (first line)
          PR_TITLE=$(echo "$COMMIT_MSG" | head -n 1)
          echo "PR_TITLE=$PR_TITLE" >> "$GITHUB_ENV"
          
          # Extract semantic type (feat, fix, etc.)
          SEMANTIC_TYPE=$(echo "$PR_TITLE" | grep -oP '^(\w+)(?:\(.*\))?:' | sed 's/://g' || echo "")
          echo "SEMANTIC_TYPE=$SEMANTIC_TYPE" >> "$GITHUB_ENV"

      - name: Check for existing PR
        id: check_pr
        run: |
          # Check if PR already exists for this branch
          EXISTING_PR=$(curl -s -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ env.BRANCH_NAME }}&base=main&state=open" | \
            jq -r '.[0].number')
          
          if [ "$EXISTING_PR" != "null" ] && [ -n "$EXISTING_PR" ]; then
            echo "Found existing PR #$EXISTING_PR for branch ${{ env.BRANCH_NAME }}"
            echo "pr_exists=true" >> "$GITHUB_OUTPUT"
            echo "pr_number=$EXISTING_PR" >> "$GITHUB_OUTPUT"
          else
            echo "No existing PR found for branch ${{ env.BRANCH_NAME }}"
            echo "pr_exists=false" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Create Pull Request
        id: create_pr
        if: steps.check_pr.outputs.pr_exists != 'true'
        run: |
          # Don't modify the existing branch - just create a PR from it
          PR_BODY=$(cat << EOF
          This PR was automatically created from branch \`${{ env.BRANCH_NAME }}\`.
          
          Original commit message:
          \`\`\`
          ${{ env.COMMIT_MESSAGE }}
          \`\`\`
          
          ## Changes
          
          <!-- List of changes in this PR -->
          
          ## Checks
          
          - [ ] Passes all required checks
          EOF
          )
          
          # Create PR using GitHub API
          PR_RESPONSE=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "$(jq -n \
              --arg title "${{ env.PR_TITLE }}" \
              --arg body "$PR_BODY" \
              --arg head "${{ env.BRANCH_NAME }}" \
              --arg base "main" \
              '{
                "title": $title,
                "body": $body,
                "head": $head,
                "base": $base,
                "draft": false
              }'
            )"
          )
          
          # Extract PR number from response
          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
          
          # Check if PR was created successfully
          if [ "$PR_NUMBER" != "null" ] && [ -n "$PR_NUMBER" ]; then
            echo "Created new PR #$PR_NUMBER for branch ${{ env.BRANCH_NAME }}"
            echo "pull-request-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          else
            echo "Failed to create PR. API response: $PR_RESPONSE"
            exit 1
          fi
      
      - name: Set PR number
        id: set_pr
        run: |
          if [[ "${{ steps.check_pr.outputs.pr_exists }}" == "true" ]]; then
            echo "Found existing PR #${{ steps.check_pr.outputs.pr_number }}"
            echo "PR_NUMBER=${{ steps.check_pr.outputs.pr_number }}" >> "$GITHUB_ENV"
          elif [[ -n "${{ steps.create_pr.outputs.pull-request-number }}" ]]; then
            echo "Using newly created PR #${{ steps.create_pr.outputs.pull-request-number }}"
            echo "PR_NUMBER=${{ steps.create_pr.outputs.pull-request-number }}" >> "$GITHUB_ENV"
          else
            echo "No PR number available. Skipping PR operations."
            echo "PR_NUMBER=" >> "$GITHUB_ENV"
          fi
      
      - name: Wait for required checks
        id: wait_checks
        if: env.PR_NUMBER != ''
        run: |
          PR_NUMBER=${{ env.PR_NUMBER }}
          echo "Waiting for required checks to complete on PR #$PR_NUMBER..."
          
          # Wait initial time for checks to be created
          echo "Waiting 10 seconds for checks to start appearing..."
          sleep 10
          
          # The expected minimum number of non-auto-merge required checks (Build + Test + Test Semantic)
          MIN_REQUIRED_CHECKS=3
          
          # Wait for checks to complete (up to 10 minutes)
          for i in {1..60}; do
            # Get commit SHA for the PR head
            PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
            
            HEAD_SHA=$(echo "$PR_INFO" | jq -r '.head.sha')
            echo "PR head commit: $HEAD_SHA"
            
            # Get all check runs for this commit
            CHECK_RUNS=$(curl -s -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/commits/$HEAD_SHA/check-runs")
            
            # Get total count of check runs
            TOTAL_CHECKS=$(echo "$CHECK_RUNS" | jq '.total_count')
            echo "Total check runs: $TOTAL_CHECKS"
            
            if [ "$TOTAL_CHECKS" = "0" ]; then
              echo "No checks found yet. Waiting..."
              sleep 5
              continue
            fi
            
            # Count completed and successful checks
            COMPLETED_CHECKS=$(echo "$CHECK_RUNS" | jq '[.check_runs[] | select(.status == "completed")] | length')
            SUCCESSFUL_CHECKS=$(echo "$CHECK_RUNS" | jq '[.check_runs[] | select(.status == "completed" and .conclusion == "success")] | length')
            FAILED_CHECKS=$(echo "$CHECK_RUNS" | jq '[.check_runs[] | select(.status == "completed" and .conclusion != "success")] | length')
            
            echo "Checks: $COMPLETED_CHECKS/$TOTAL_CHECKS completed, $SUCCESSFUL_CHECKS successful, $FAILED_CHECKS failed"
            
            # Debug: Output all check names for better debugging
            echo "All check names:"
            echo "$CHECK_RUNS" | jq -r '.check_runs[] | "\(.id): \(.name), status: \(.status), conclusion: \(.conclusion)"'
            
            # The exact check name for our workflow is "Create and Merge PR" (not the full workflow/job name format)
            OUR_WORKFLOW_NAME="Create and Merge PR"
            
            # Count in-progress checks that match our workflow exactly
            AUTO_MERGE_IN_PROGRESS=$(echo "$CHECK_RUNS" | jq --arg name "$OUR_WORKFLOW_NAME" '[.check_runs[] | select(.status != "completed" and .name == $name)] | length')
            
            # Get total of our specific workflow checks
            TOTAL_AUTO_MERGE_CHECKS=$(echo "$CHECK_RUNS" | jq --arg name "$OUR_WORKFLOW_NAME" '[.check_runs[] | select(.name == $name)] | length')
            
            # Calculate non-auto-merge checks more precisely
            NON_AUTO_MERGE_TOTAL=$((TOTAL_CHECKS - TOTAL_AUTO_MERGE_CHECKS))
            NON_AUTO_MERGE_COMPLETED=$(echo "$CHECK_RUNS" | jq --arg name "$OUR_WORKFLOW_NAME" '[.check_runs[] | select(.status == "completed" and .name != $name)] | length')
            
            echo "Auto-merge in progress: $AUTO_MERGE_IN_PROGRESS"
            echo "Total auto-merge checks: $TOTAL_AUTO_MERGE_CHECKS"
            echo "Non-auto-merge checks: $NON_AUTO_MERGE_COMPLETED/$NON_AUTO_MERGE_TOTAL completed"
            
            # If any checks failed, exit
            if [ "$FAILED_CHECKS" != "0" ]; then
              echo "Some checks failed. Aborting merge."
              exit 1
            fi
            
            # Make sure we have at least the minimum required number of non-auto-merge checks
            if [ "$NON_AUTO_MERGE_TOTAL" -lt "$MIN_REQUIRED_CHECKS" ]; then
              echo "Waiting for more checks to appear. Expected at least $MIN_REQUIRED_CHECKS, but found $NON_AUTO_MERGE_TOTAL"
              sleep 5
              continue
            fi
            
            # Proceed ONLY if either:
            # 1. ALL checks are complete, OR
            # 2. All non-auto-merge checks are complete AND exactly one auto-merge check is still running
            if [ "$COMPLETED_CHECKS" = "$TOTAL_CHECKS" ] || [ "$NON_AUTO_MERGE_COMPLETED" = "$NON_AUTO_MERGE_TOTAL" -a "$AUTO_MERGE_IN_PROGRESS" = "1" -a "$TOTAL_AUTO_MERGE_CHECKS" = "1" ]; then
              echo "All required checks completed successfully (except possibly our own workflow)!"
              
              # Check if the PR is mergeable
              MERGEABLE=$(echo "$PR_INFO" | jq -r '.mergeable // false')
              MERGEABLE_STATE=$(echo "$PR_INFO" | jq -r '.mergeable_state // "unknown"')
              
              echo "PR mergeable status: $MERGEABLE, state: $MERGEABLE_STATE"
              
              # If PR is clean or has passed all checks, we can proceed
              if [ "$MERGEABLE" = "true" ] || [ "$MERGEABLE_STATE" = "clean" ]; then
                echo "PR is ready to be merged!"
                break
              elif [ "$MERGEABLE_STATE" = "blocked" ]; then
                echo "PR is blocked, but all checks have passed. Attempting to merge anyway."
                break
              else
                echo "All checks passed but PR is not mergeable. State: $MERGEABLE_STATE"
                # Continue anyway since checks passed
                break
              fi
            fi
            
            # Check if we're out of time
            if [ $i -eq 60 ]; then
              echo "Timeout waiting for checks to complete."
              exit 1
            fi
            
            echo "Waiting for all checks to complete (attempt $i/60)..."
            sleep 10
          done
      
      - name: Determine semantic merge message
        id: merge_message
        if: steps.wait_checks.outcome == 'success'
        run: |
          # Check if SEMANTIC_TYPE is set and not empty
          if [ -n "${SEMANTIC_TYPE:-}" ]; then
            echo "Using existing semantic type: ${SEMANTIC_TYPE}"
            MERGE_MSG="${COMMIT_MESSAGE:-}"
          else
            # Default to fix: if no semantic type is detected
            echo "No semantic type detected, defaulting to fix:"
            MERGE_MSG="fix: ${PR_TITLE:-}"
          fi
          
          echo "MERGE_MESSAGE<<EOF" >> "$GITHUB_ENV"
          echo "$MERGE_MSG" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      
      - name: Merge Pull Request
        if: steps.merge_message.outcome == 'success'
        run: |
          PR_NUMBER=${PR_NUMBER:-}
          
          # Create properly escaped JSON payload
          MERGE_TITLE=$(echo "${MERGE_MESSAGE:-}" | head -n 1)
          
          # Create JSON payload with jq to handle escaping properly
          JSON_PAYLOAD=$(jq -n \
            --arg title "$MERGE_TITLE" \
            '{
              "commit_title": $title,
              "commit_message": "",
              "merge_method": "squash"
            }')
          
          # Merge the PR with the semantic commit message
          RESPONSE=$(curl -s -w "\n%{http_code}" -X PUT \
            -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
            -d "$JSON_PAYLOAD")
          
          # Extract status code and response body
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | sed '$ d')
          
          echo "Response body: $RESPONSE_BODY"
          echo "Status code: $HTTP_STATUS"
          
          # Check if merge was successful (2xx status code)
          if [[ $HTTP_STATUS -ge 200 && $HTTP_STATUS -lt 300 ]]; then
            echo "Successfully merged PR #$PR_NUMBER with semantic message"
          else
            echo "Failed to merge PR #$PR_NUMBER. Status: $HTTP_STATUS"
            echo "Error: $RESPONSE_BODY"
            exit 1
          fi
      
      - name: Delete branch
        if: success() && steps.merge_message.outcome == 'success'
        run: |
          # Extract branch name from GITHUB_REF to ensure we have it
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Deleting branch $BRANCH_NAME after successful merge..."
          
          # Delete the branch using GitHub API
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.PR_CREATION_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
          
          echo "Branch $BRANCH_NAME has been deleted"