name: Build Job

on:
  workflow_call:
    outputs:
      build_success:
        description: "Whether the build succeeded"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.check_builds.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8.15.4'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build all packages
        run: |
          # Build packages in correct order with error checking
          echo "🏗️ Building workspace packages..."
          
          echo "Building blorkpack..."
          pnpm --filter "@littlecarlito/blorkpack" build
          if [ ! -d "packages/blorkpack/dist" ] || [ ! -f "packages/blorkpack/dist/index.js" ]; then
            echo "❌ blorkpack build failed - dist directory or index.js missing"
            exit 1
          fi
          echo "✅ blorkpack build completed successfully"
          
          echo "Building blorktools..."
          pnpm --filter "@littlecarlito/blorktools" build
          if [ ! -d "packages/blorktools/dist" ]; then
            echo "❌ blorktools build failed - dist directory missing"
            exit 1
          fi
          echo "✅ blorktools build completed successfully"
          
          echo "Building portfolio..."
          pnpm --filter "@littlecarlito/portfolio" build
          if [ ! -d "apps/portfolio/dist" ]; then
            echo "❌ portfolio build failed - dist directory missing"
            exit 1
          fi
          echo "✅ portfolio build completed successfully"
      
      - name: Verify Builds
        id: check_builds
        run: |
          # Check package builds
          for pkg in blorkpack blorktools; do
            if [ ! -d "packages/$pkg/dist" ]; then
              echo "❌ $pkg build failed - dist directory missing"
              echo "success=false" >> $GITHUB_OUTPUT
              exit 1
            fi
            
            # Specifically check for index.js file in blorkpack
            if [ "$pkg" = "blorkpack" ] && [ ! -f "packages/$pkg/dist/index.js" ]; then
              echo "❌ $pkg build failed - dist/index.js file missing"
              ls -la packages/$pkg/dist/
              echo "success=false" >> $GITHUB_OUTPUT
              exit 1
            fi
            
            echo "✅ $pkg build verified"
          done

          # List contents of blorkpack dist for debugging
          echo "📂 Contents of packages/blorkpack/dist:"
          ls -la packages/blorkpack/dist/

          # Check portfolio build
          if [ ! -d "apps/portfolio/dist" ]; then
            echo "❌ Portfolio build failed - dist directory missing"
            echo "success=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "✅ Portfolio build verified"
          
          # Check for source files in portfolio dist
          SOURCE_FILES=$(find apps/portfolio/dist -name "*.ts" -o -name "*.tsx" -o -name "*.js.map" | grep -v "node_modules" || true)
          if [ ! -z "$SOURCE_FILES" ]; then
            echo "⚠️ Warning: Source files found in dist folder:"
            echo "$SOURCE_FILES"
          else
            echo "✅ No source files in dist directory"
          fi
          
          echo "success=true" >> $GITHUB_OUTPUT
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builds
          path: |
            packages/blorkpack/dist
            packages/blorktools/dist
            apps/portfolio/dist
          retention-days: 1 