name: Unpublish Multiple Package Versions

on:
  workflow_dispatch:
    inputs:
      packages-list:
        description: 'JSON array of package versions to unpublish: [{"package":"blorktools","version":"1.13.0"},{"package":"blorkboard","version":"1.12.1"}]'
        required: true
        type: string
      unpublish-tags:
        description: 'Also delete corresponding git tags'
        required: false
        type: boolean
        default: true
      dry-run:
        description: 'Dry run (show what would happen without doing it)'
        required: false
        type: boolean
        default: false

jobs:
  parse-inputs:
    name: Parse Inputs and Prepare Jobs
    runs-on: ubuntu-latest
    outputs:
      packages-matrix: ${{ steps.parse.outputs.packages-matrix }}
    steps:
      - name: Parse package list
        id: parse
        run: |
          # Validate JSON input
          echo '${{ github.event.inputs.packages-list }}' | jq -e . > /dev/null || {
            echo "Error: Invalid JSON input in packages-list"
            exit 1
          }
          
          # Generate matrix for dynamic jobs
          echo "packages-matrix=$(echo '${{ github.event.inputs.packages-list }}')" >> $GITHUB_OUTPUT
          
          # Display what we're going to unpublish
          echo "Will unpublish the following packages:"
          echo '${{ github.event.inputs.packages-list }}' | jq -r '.[] | "- \(.package)@\(.version)"'

  unpublish-packages:
    name: Unpublish Package Versions
    needs: parse-inputs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        package-info: ${{ fromJson(needs.parse-inputs.outputs.packages-matrix) }}
      fail-fast: false
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VERSION_TOKEN }}
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@littlecarlito'
      
      # Setup explicit npm authentication
      - name: Configure NPM Auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.VERSION_TOKEN }}" > ~/.npmrc
          echo "@littlecarlito:registry=https://npm.pkg.github.com" >> ~/.npmrc
          cat ~/.npmrc
        
      # Try direct npm unpublish first
      - name: Direct NPM Unpublish
        id: direct_unpublish
        continue-on-error: true
        run: |
          echo "Attempting direct npm unpublish..."
          
          PACKAGE="${{ matrix.package-info.package }}"
          VERSION="${{ matrix.package-info.version }}"
          
          # Normalize package name if needed
          if [[ ! "$PACKAGE" == @littlecarlito* ]]; then
            PACKAGE="@littlecarlito/$PACKAGE"
            echo "Normalized package name to $PACKAGE"
          fi
          
          if [[ "${{ github.event.inputs.dry-run }}" == "true" ]]; then
            echo "[DRY RUN] Would unpublish $PACKAGE@$VERSION"
            echo "unpublished=false" >> $GITHUB_OUTPUT
          else
            npm unpublish --force "$PACKAGE@$VERSION" || {
              echo "Direct unpublish failed, will try alternative method"
              echo "unpublished=false" >> $GITHUB_OUTPUT
              exit 1
            }
            echo "Successfully unpublished $PACKAGE@$VERSION"
            echo "unpublished=true" >> $GITHUB_OUTPUT
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VERSION_TOKEN }}
      
      # Try the action as fallback
      - name: Unpublish package using action
        if: steps.direct_unpublish.outputs.unpublished != 'true'
        id: unpublish
        uses: ./.github/actions/unpublish-package
        with:
          github-token: ${{ secrets.VERSION_TOKEN }}
          package: ${{ matrix.package-info.package }}
          version: ${{ matrix.package-info.version }}
          unpublish-tag: ${{ github.event.inputs.unpublish-tags }}
          dry-run: ${{ github.event.inputs.dry-run }}
      
      # Delete tag if requested and direct unpublish succeeded
      - name: Delete Git tag (after direct unpublish)
        if: steps.direct_unpublish.outputs.unpublished == 'true' && github.event.inputs.unpublish-tags == 'true' && github.event.inputs.dry-run != 'true'
        run: |
          PACKAGE="${{ matrix.package-info.package }}"
          VERSION="${{ matrix.package-info.version }}"
          
          # Normalize package name if needed
          if [[ ! "$PACKAGE" == @littlecarlito* ]]; then
            PACKAGE="@littlecarlito/$PACKAGE"
          fi
          
          # Try both tag formats
          TAG_NAME="${PACKAGE}@${VERSION}"
          CLEAN_PKG_NAME=$(echo "$PACKAGE" | sed 's/@//g' | sed 's/\//-/g')
          ALT_TAG_NAME="${CLEAN_PKG_NAME}@${VERSION}"
          
          echo "Checking for tag: $TAG_NAME"
          git tag -d "$TAG_NAME" 2>/dev/null || echo "Tag $TAG_NAME doesn't exist locally"
          git push --delete origin "$TAG_NAME" 2>/dev/null || echo "Tag $TAG_NAME doesn't exist on remote"
          
          echo "Checking for alternative tag: $ALT_TAG_NAME"
          git tag -d "$ALT_TAG_NAME" 2>/dev/null || echo "Tag $ALT_TAG_NAME doesn't exist locally"
          git push --delete origin "$ALT_TAG_NAME" 2>/dev/null || echo "Tag $ALT_TAG_NAME doesn't exist on remote"
          
  summary:
    name: Summary of Unpublished Packages
    needs: [parse-inputs, unpublish-packages]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        run: |
          echo "# Unpublish Operation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following packages were processed:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Display each package directly from the input
          echo '${{ github.event.inputs.packages-list }}' | jq -r '.[] | "- \(.package)@\(.version)"' >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event.inputs.dry-run }}" == "true" ]]; then
            echo "**Note**: This was a dry run. No actual changes were made." >> $GITHUB_STEP_SUMMARY
          else
            echo "**Note**: Packages were unpublished from the registry." >> $GITHUB_STEP_SUMMARY
            if [[ "${{ github.event.inputs.unpublish-tags }}" == "true" ]]; then
              echo "Corresponding Git tags were also deleted." >> $GITHUB_STEP_SUMMARY
            fi
          fi
          
      # Report failure using the new action    
      - name: Report failure
        if: failure()
        uses: ./.github/actions/report-workflow-results
        with:
          workflow-name: 'Manual Unpublish Packages'
          result: 'failure'
          branch: ${{ github.ref_name }}
          summary: 'Failed to unpublish multiple packages - See workflow run for details'
          source: 'dispatch'
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          github-token: ${{ secrets.VERSION_TOKEN }} 