name: Manual Clean and Generate Changesets

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  clean-and-generate:
    name: Clean and Generate Changesets
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PACKAGE_TOKEN }}
      
      - name: Setup environment
        id: setup
        run: |
          # Run the setup script and filter only properly formatted output lines 
          bash .github/scripts/maintenance/setup-environment.sh \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --node-version "20.x" \
            --pnpm-version "8.15.4" \
            --registry-url "https://npm.pkg.github.com" \
            --scope "@littlecarlito" 2>&1 | grep -E "^[a-zA-Z0-9_-]+=.+" >> $GITHUB_OUTPUT || true

      # Create a unique branch for new changesets
      - name: Create branch for changesets
        id: create_branch
        run: |
          # Use a unique branch name with timestamp to avoid conflicts
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="chore/generate-changesets-$TIMESTAMP"
          echo "Using branch name: $BRANCH_NAME"
          
          # Create and switch to the new branch
          git checkout -b $BRANCH_NAME
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Clear all unreleased changeset files
      - name: Clear unreleased changesets
        run: |
          echo "Cleaning all unreleased changeset files"
          rm -rf .changeset/*.md
          # Create README.md if it doesn't exist
          [ ! -f .changeset/README.md ] && echo "---\n# Changesets\n\nThis directory contains changeset files generated by the changeset tool." > .changeset/README.md
          
          # Commit the changes to clear changesets
          git add .changeset/
          git commit -m "chore: clear all unreleased changesets" || echo "No changes to commit"
      
      # Generate new changesets based on unreleased changes
      - name: Generate changesets for unreleased changes
        id: generate_changesets
        uses: ./.github/actions/scan-and-generate-changesets
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # Use empty force-base-commit to auto-detect from tags/releases
          force-base-commit: ""
          auto-changeset-prefix: 'auto-'

      # Check if changesets were created
      - name: Check if changesets were created
        id: check_changesets
        run: |
          CHANGESET_COUNT=$(find .changeset -name "*.md" ! -name "README.md" ! -name "config.json" | wc -l)
          echo "changeset_count=$CHANGESET_COUNT" >> $GITHUB_OUTPUT
          
          if [ "$CHANGESET_COUNT" -gt "0" ]; then
            echo "Found $CHANGESET_COUNT changesets to commit"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changesets were created"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      
      # Commit the generated changesets if any were created
      - name: Commit generated changesets
        if: steps.check_changesets.outputs.has_changes == 'true'
        run: |
          git add .changeset/
          git commit -m "chore: generate changesets for unreleased changes"
          
          # Push the branch
          git push origin ${{ steps.create_branch.outputs.branch_name }}
      
      # Create PR using the manage-pull-request action
      - name: Create PR
        id: create_pr
        if: steps.check_changesets.outputs.has_changes == 'true'
        uses: ./.github/actions/manage-pull-request
        with:
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          repository: ${{ github.repository }}
          base-branch: main
          head-branch: ${{ steps.create_branch.outputs.branch_name }}
          title: 'chore: generate changesets for unreleased changes'
          body: 'This PR generates changesets for unreleased changes since the last release or tag for each package, then cleans up existing changesets to start fresh.'
      
      # Add status checks to PR for workflow compatibility
      - name: Add status checks
        if: steps.check_changesets.outputs.has_changes == 'true'
        run: |
          bash .github/scripts/branch/force-status.sh \
            --token "${{ secrets.GITHUB_TOKEN }}" \
            --repo "${{ github.repository }}" \
            --sha "${{ steps.create_pr.outputs.commit-sha }}" \
            --contexts '["Build Packages", "Test / Run Tests", "Test Changesets"]' \
            --descriptions '["Build completed successfully (via manual-clean-changesets)", "Tests passed successfully (via manual-clean-changesets)", "Changesets validated successfully (via manual-clean-changesets)"]'
      
      # Wait for checks to complete before merging
      - name: Wait for checks to complete
        if: steps.check_changesets.outputs.has_changes == 'true'
        run: |
          bash .github/scripts/branch/wait-checks.sh \
            --repo "${{ github.repository }}" \
            --sha "${{ steps.create_pr.outputs.commit-sha }}" \
            --workflow "Manual Clean and Generate Changesets" \
            --timeout "300" \
            --min-checks "3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Merge the PR using the merge-pull-request action
      - name: Merge pull request
        if: steps.check_changesets.outputs.has_changes == 'true'
        uses: ./.github/actions/merge-pull-request
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          repository: ${{ github.repository }}
          pr-number: ${{ steps.create_pr.outputs.pr-number }}
          merge-method: 'squash'
          delete-branch: 'true'
          auto-merge: 'true'
      
      # Output status message for completion
      - name: Status check
        run: |
          if [ "${{ steps.check_changesets.outputs.has_changes }}" == "true" ]; then
            echo "Successfully generated changesets and created PR #${{ steps.create_pr.outputs.pr-number }}"
            echo "After merging, main-pipeline.yml will run and publish packages with direct publishing."
          else
            echo "No unreleased changes detected or no changesets were generated."
          fi 