name: Manual Clean and Generate Changesets

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  clean-and-generate:
    name: Clean and Generate Changesets
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PACKAGE_TOKEN }}
      
      - name: Setup environment
        id: setup
        run: |
          # Run the setup script and filter only properly formatted output lines 
          bash .github/scripts/maintenance/setup-environment.sh \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --node-version "20.x" \
            --pnpm-version "8.15.4" \
            --registry-url "https://npm.pkg.github.com" \
            --scope "@littlecarlito" 2>&1 | grep -E "^[a-zA-Z0-9_-]+=.+" >> $GITHUB_OUTPUT || true

      # Create a unique branch for new changesets
      - name: Create branch for changesets
        id: create_branch
        if: steps.check_changesets.outputs.has_changes == 'true'
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="chore/generate-changesets-$TIMESTAMP"
          OUTPUT=$(bash .github/scripts/version/create-changeset-branch.sh --branch-name "$BRANCH_NAME")
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Clear all unreleased changeset files
      - name: Clear unreleased changesets
        run: |
          echo "Cleaning all unreleased changeset files"
          rm -rf .changeset/*.md
          # Create README.md if it doesn't exist
          [ ! -f .changeset/README.md ] && echo "---\n# Changesets\n\nThis directory contains changeset files generated by the changeset tool." > .changeset/README.md
          
          # Commit the changes to clear changesets
          git add .changeset/
          git commit -m "chore: clear all unreleased changesets" || echo "No changes to commit"
      
      # Use the check-conventional-commits script to get base commit info
      - name: Check conventional commits
        id: check_commits
        run: |
          bash .github/scripts/version/check-conventional-commits.sh \
            --base-commit "" \
            --auto-changeset-prefix "auto-" > >(tee /dev/stderr) | grep -E "^(base_commit|conventional_count)=" >> $GITHUB_OUTPUT || true
      
      # Use the existing scan-and-generate-changesets action
      - name: Generate changesets for unreleased changes
        id: generate_changesets
        uses: ./.github/actions/scan-and-generate-changesets
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          # Empty force-base-commit triggers auto-detection from tags
          force-base-commit: ""
          auto-changeset-prefix: 'auto-'
      
      # Use check-changesets script to verify what was created
      - name: Check if changesets were created
        id: check_changesets
        run: |
          bash .github/scripts/version/check-changesets.sh | grep -E "^changeset_count=" >> $GITHUB_OUTPUT || true
          
          # Add additional debug information
          CHANGESET_COUNT=$(find .changeset -name "*.md" ! -name "README.md" ! -name "config.json" | wc -l)
          echo "==== CHANGESET DEBUG INFO ===="
          echo "Changeset count: $CHANGESET_COUNT"
          
          # Check if there are actual changes to commit
          CHANGES=$(git status --porcelain .changeset/)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected in .changeset directory:"
            echo "$CHANGES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected in .changeset directory"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          
          # List any changesets that exist
          if [ "$CHANGESET_COUNT" -gt "0" ]; then
            echo "Existing changesets:"
            find .changeset -name "*.md" ! -name "README.md" ! -name "config.json" | xargs cat
          fi
          echo "==== END CHANGESET DEBUG INFO ===="
      
      # Validate changesets using existing script
      - name: Validate changesets
        id: validate_changesets
        if: steps.check_changesets.outputs.changeset_count > '0'
        run: |
          bash .github/scripts/version/validate-changesets.sh
      
      # Use commit-changeset script to save changes
      - name: Commit generated changesets
        id: commit_changesets
        if: steps.check_changesets.outputs.has_changes == 'true'
        run: |
          BRANCH_NAME="${{ steps.create_branch.outputs.branch_name }}"
          OUTPUT=$(bash .github/scripts/version/commit-changeset.sh --branch-name "$BRANCH_NAME")
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          
          # Extract and check if commit was successful 
          COMMIT_SUCCESS=$(echo "$OUTPUT" | grep "^commit_success=" | cut -d= -f2)
          if [ "$COMMIT_SUCCESS" == "true" ]; then
            echo "pushed_changes=true" >> $GITHUB_OUTPUT
          else
            echo "pushed_changes=false" >> $GITHUB_OUTPUT
          fi
      
      # Create PR using the manage-pull-request action
      - name: Create PR
        id: create_pr
        if: steps.check_changesets.outputs.has_changes == 'true' && steps.commit_changesets.outputs.pushed_changes == 'true'
        uses: ./.github/actions/manage-pull-request
        with:
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          repository: ${{ github.repository }}
          base-branch: main
          head-branch: ${{ steps.create_branch.outputs.branch_name }}
          title: 'chore: generate changesets for unreleased changes'
          body: 'This PR generates changesets for unreleased changes since the last release or tag for each package, then cleans up existing changesets to start fresh.'
      
      # Add status checks to PR for workflow compatibility
      - name: Add status checks
        if: steps.check_changesets.outputs.has_changes == 'true' && steps.commit_changesets.outputs.pushed_changes == 'true' && steps.create_pr.outputs.pr-number != ''
        run: |
          bash .github/scripts/branch/force-status.sh \
            --token "${{ secrets.GITHUB_TOKEN }}" \
            --repo "${{ github.repository }}" \
            --sha "${{ steps.create_pr.outputs.commit-sha }}" \
            --contexts '["Build Packages", "Test / Run Tests", "Test Changesets"]' \
            --descriptions '["Build completed successfully (via manual-clean-changesets)", "Tests passed successfully (via manual-clean-changesets)", "Changesets validated successfully (via manual-clean-changesets)"]'
      
      # Wait for checks to complete before merging
      - name: Wait for checks to complete
        if: steps.check_changesets.outputs.has_changes == 'true' && steps.commit_changesets.outputs.pushed_changes == 'true' && steps.create_pr.outputs.pr-number != ''
        run: |
          bash .github/scripts/branch/wait-checks.sh \
            --repo "${{ github.repository }}" \
            --sha "${{ steps.create_pr.outputs.commit-sha }}" \
            --workflow "Manual Clean and Generate Changesets" \
            --timeout "300" \
            --min-checks "3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Merge the PR using the merge-pull-request action
      - name: Merge pull request
        if: steps.check_changesets.outputs.has_changes == 'true' && steps.commit_changesets.outputs.pushed_changes == 'true' && steps.create_pr.outputs.pr-number != ''
        uses: ./.github/actions/merge-pull-request
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          repository: ${{ github.repository }}
          pr-number: ${{ steps.create_pr.outputs.pr-number }}
          merge-method: 'squash'
          delete-branch: 'true'
          auto-merge: 'true'
      
      # Output status message for completion
      - name: Status check
        run: |
          if [ "${{ steps.check_changesets.outputs.has_changes }}" == "true" ] && [ "${{ steps.commit_changesets.outputs.pushed_changes }}" == "true" ] && [ -n "${{ steps.create_pr.outputs.pr-number }}" ]; then
            echo "Successfully generated changesets and created PR #${{ steps.create_pr.outputs.pr-number }}"
            echo "After merging, main-pipeline.yml will run and publish packages with direct publishing."
          else
            if [ "${{ steps.check_changesets.outputs.has_changes }}" != "true" ]; then
              echo "No changes to commit: No new changesets were needed or could be created."
            elif [ "${{ steps.commit_changesets.outputs.pushed_changes }}" != "true" ]; then
              echo "Failed to push changes: Changes were detected but could not be committed."
            else
              echo "Failed to create PR: Changes were committed but PR creation failed."
            fi
            echo "No action was needed or the process could not complete."
          fi 