name: Push Create PR

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.create_pr.outputs.pr-number }}
      merge-title: ${{ steps.create_pr.outputs.merge-title }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PR_CREATION_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          fetch-depth: 0

      - name: Create PR and wait for checks
        id: create_pr
        uses: ./.github/actions/create-pr
        with:
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          repository: ${{ github.repository }}
          head-branch: ${{ github.ref_name }}
          min-checks: 3
          timeout: 600
      
      # Directly merge the PR using the merge-pr action
      - name: Merge PR
        uses: ./.github/actions/merge-pr
        with:
          github-token: ${{ secrets.PR_CREATION_TOKEN }}
          repository: ${{ github.repository }}
          pr-number: ${{ steps.create_pr.outputs.pr-number }}
          commit-title: ${{ steps.create_pr.outputs.merge-title }}
          merge-method: squash
          delete-branch: true 