name: Report Pipeline Results [DEPRECATED]

# DEPRECATED: This workflow has been converted to a reusable action.
# Please use the new .github/actions/report-workflow-results action instead.
# This file is kept for backward compatibility but will be removed in the future.

on:
  workflow_run:
    workflows:
      - "Push and Create PR"
      - "Manual Clean and Generate Changesets"
    types:
      - completed
  workflow_dispatch:
    inputs:
      result:
        description: 'Pipeline result (success/failure)'
        required: true
        default: 'success'
        type: choice
        options:
          - 'success'
          - 'failure'
      workflow_name:
        description: 'Name of the workflow that triggered this report'
        required: true
        default: 'Manual Trigger'
      summary:
        description: 'Pipeline summary'
        required: false
        default: 'Manually triggered report'

permissions:
  contents: read
  actions: read

jobs:
  redirect-to-action:
    name: Redirect to Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Display warning
        run: |
          echo "::warning::This workflow is deprecated and will be removed in the future. Please use the .github/actions/report-workflow-results action instead."
          
      - name: Forward to report-workflow-results action
        uses: ./.github/actions/report-workflow-results
        with:
          workflow-name: ${{ github.event.inputs.workflow_name || github.event.workflow_run.name }}
          result: ${{ github.event.inputs.result || github.event.workflow_run.conclusion }}
          branch: ${{ github.event.workflow_run.head_branch || github.ref_name }}
          summary: ${{ github.event.inputs.summary || '' }}
          source: ${{ github.event_name == 'workflow_run' && 'webhook' || 'dispatch' }}
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          github-token: ${{ secrets.PR_CREATION_TOKEN }} 