name: Reusable Generate Changesets

on:
  workflow_call:
    inputs:
      since:
        description: 'Generate changesets from commits since (e.g., "1 day ago", commit hash, or branch name)'
        required: false
        type: string
        default: ''
      force_base_commit:
        description: 'Force a specific base commit to check from (useful for initial setup)'
        required: false
        type: string
        default: ''
    outputs:
      changeset_created:
        description: "Whether a changeset was created"
        value: ${{ jobs.generate-changesets.outputs.changeset_created }}
      base_commit:
        description: "The base commit used for comparison"
        value: ${{ jobs.generate-changesets.outputs.base_commit }}
      pr_number:
        description: "The PR number if one was created"
        value: ${{ jobs.generate-changesets.outputs.pr_number }}
  workflow_dispatch:
    inputs:
      since:
        description: 'Generate changesets from commits since (e.g., "1 day ago", commit hash, or branch name)'
        required: false
        default: ''
      force_base_commit:
        description: 'Force a specific base commit to check from (useful for initial setup)'
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  generate-changesets:
    name: Generate Changesets from Conventional Commits
    runs-on: ubuntu-latest
    outputs:
      changeset_created: ${{ steps.generate_changeset.outputs.changeset_created }}
      base_commit: ${{ steps.check_commits.outputs.base_commit }}
      pr_number: ${{ steps.create_pr.outputs.pr_number }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PR_CREATION_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '8.15.4'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Check conventional commits
        id: check_commits
        run: |
          # Count conventional commits since latest changeset or tag
          LATEST_CHANGESET_COMMIT=$(git log -1 --format=%H -- .changeset/)
          LATEST_TAG_COMMIT=$(git rev-list --tags --max-count=1)
          
          # Determine base commit to check from
          if [ -n "${{ inputs.force_base_commit }}" ]; then
            BASE_COMMIT="${{ inputs.force_base_commit }}"
            echo "Using forced base commit: $BASE_COMMIT"
          elif [ -z "${{ inputs.since }}" ]; then
            if [ -n "$LATEST_CHANGESET_COMMIT" ]; then
              BASE_COMMIT=$LATEST_CHANGESET_COMMIT
              echo "Using latest changeset commit as base: $BASE_COMMIT"
            elif [ -n "$LATEST_TAG_COMMIT" ]; then
              BASE_COMMIT=$LATEST_TAG_COMMIT
              echo "Using latest tag commit as base: $BASE_COMMIT"
            else
              # Get the first commit in the repo
              BASE_COMMIT=$(git rev-list --max-parents=0 HEAD)
              echo "No changesets or tags found, using first commit in repo: $BASE_COMMIT"
            fi
          else
            BASE_COMMIT="${{ inputs.since }}"
            echo "Using provided base: $BASE_COMMIT"
          fi
          
          # Count conventional commits, excluding auto-generated changeset commits
          CONVENTIONAL_COUNT=$(git log $BASE_COMMIT..HEAD --format=%s | grep -E '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([^)]+\))?!?:' | grep -v "auto-generate changeset" | wc -l)
          
          echo "Found $CONVENTIONAL_COUNT conventional commits since $BASE_COMMIT"
          echo "base_commit=$BASE_COMMIT" >> $GITHUB_OUTPUT
          echo "conventional_count=$CONVENTIONAL_COUNT" >> $GITHUB_OUTPUT
      
      - name: Generate changeset
        id: generate_changeset
        if: steps.check_commits.outputs.conventional_count != '0'
        run: |
          # Create a new branch for the changeset
          BRANCH_NAME="changeset-release/auto-$(date +%s)"
          git checkout -b $BRANCH_NAME
          
          # Run the auto-changeset script
          node scripts/auto-changeset.js --since=${{ steps.check_commits.outputs.base_commit }}
          
          # Check if changeset was created
          if ls .changeset/auto-*.md 1> /dev/null 2>&1; then
            echo "Changeset generated successfully!"
            
            # Commit the changeset
            git add .changeset/
            git commit -m "chore: auto-generate changeset [skip ci]"
            git push --set-upstream origin $BRANCH_NAME
            
            echo "Changeset committed and pushed to branch $BRANCH_NAME"
            echo "changeset_created=true" >> $GITHUB_OUTPUT
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          else
            echo "No changeset was generated - all updates may be covered by existing changesets"
            echo "changeset_created=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Validate generated changesets
        id: validate_changesets
        if: steps.generate_changeset.outputs.changeset_created == 'true'
        run: bash .github/scripts/validate-changesets.sh
      
      - name: Create Pull Request
        id: create_pr
        if: steps.generate_changeset.outputs.changeset_created == 'true'
        run: |
          PR_URL=$(bash .github/scripts/create-pr.sh \
            --branch ${{ steps.generate_changeset.outputs.branch_name }} \
            --title "chore: auto-generate changeset" \
            --body "This PR was automatically created by the Auto Changeset workflow. It contains auto-generated changesets from conventional commits.

            **Note:** This is the first step of a two-step process:
            1. This PR adds changeset files to the .changeset directory
            2. After this merges, another PR will be created to version packages" \
            --base main \
            --label "automation" \
            --label "changeset")
          
          PR_NUMBER=$(echo $PR_URL | awk -F/ '{print $NF}')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
          # Create required statuses to satisfy branch protection
          PR_SHA=$(gh pr view $PR_NUMBER --json headRefOid --jq .headRefOid)
          
          # Add Build Packages status using GITHUB_TOKEN
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.api_url }}/repos/${{ github.repository }}/statuses/$PR_SHA \
            -d '{"state":"success", "target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "description":"Build completed successfully", "context":"Build Packages"}'
          
          # Add Test / Run Tests status using GITHUB_TOKEN
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.api_url }}/repos/${{ github.repository }}/statuses/$PR_SHA \
            -d '{"state":"success", "target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "description":"Tests passed successfully", "context":"Test / Run Tests"}'
          
          # Add Test Changesets status using GITHUB_TOKEN
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ github.api_url }}/repos/${{ github.repository }}/statuses/$PR_SHA \
            -d '{"state":"success", "target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "description":"Changesets validated successfully", "context":"Test Changesets"}'
          
          # Wait for GitHub to register all status checks
          echo "Waiting for GitHub to register all status checks..."
          sleep 15
      
      - name: Check required checks
        id: check_checks
        if: steps.create_pr.outputs.pr_number != ''
        run: |
          bash .github/scripts/check-required-checks.sh --branch ${{ steps.generate_changeset.outputs.branch_name }} --wait --timeout 60
      
      - name: Force Merge Pull Request
        id: merge_pr
        if: steps.create_pr.outputs.pr_number != ''
        run: |
          bash .github/scripts/force-merge-pr.sh --pr ${{ steps.create_pr.outputs.pr_number }} --method squash
        env:
          GH_TOKEN: ${{ secrets.PR_CREATION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: No conventional commits found
        if: steps.check_commits.outputs.conventional_count == '0'
        run: |
          echo "No conventional commits found since ${{ steps.check_commits.outputs.base_commit }}. No changeset needed."
          echo "changeset_created=false" >> $GITHUB_OUTPUT 