name: Reusable Merge PR

on:
  workflow_call:
    inputs:
      pr-number:
        description: 'PR number to merge'
        required: true
        type: string
      commit-title:
        description: 'Title for the merge commit'
        required: true
        type: string
      merge-method:
        description: 'Merge method to use (merge, squash, rebase)'
        required: false
        type: string
        default: 'squash'
      delete-branch:
        description: 'Whether to delete the branch after merging'
        required: false
        type: boolean
        default: true
    secrets:
      PR_CREATION_TOKEN:
        description: 'GitHub token with permissions to merge PRs'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr:
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.PR_CREATION_TOKEN }}
      
      - name: Merge Pull Request
        shell: bash
        run: |
          bash .github/scripts/pr/force-merge.sh \
            --token "${{ secrets.PR_CREATION_TOKEN }}" \
            --repo "${{ github.repository }}" \
            --pr-number "${{ inputs.pr-number }}" \
            --commit-title "${{ inputs.commit-title }}" \
            --merge-method "${{ inputs.merge-method }}" \
            --delete-branch "${{ inputs.delete-branch }}" 