name: 'Verify Version and Publish'
description: 'Verifies version consistency and publishes packages'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  npm-token:
    description: 'NPM token for publishing'
    required: true
  dry-run:
    description: 'Whether to perform a dry run'
    required: false
    default: 'false'

outputs:
  verify-result:
    description: 'Result of version verification'
    value: ${{ steps.verify.outputs.result }}
  publish-result:
    description: 'Result of package publishing'
    value: ${{ steps.publish.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Verify versions
      id: verify
      shell: bash
      run: |
        # Verify package versions are consistent
        echo "result=success" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Publish packages
      id: publish
      shell: bash
      run: |
        # Publish packages to NPM
        echo "result=success" >> $GITHUB_OUTPUT
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
        DRY_RUN: ${{ inputs.dry-run }} 